default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Kimchistan-Backend_development

test:
  <<: *default
  database: Kimchistan-Backend_test

production:
  <<: *default
  database: Kimchistan-Backend_production
  username: Kimchistan-Backend
  password: <%= ENV['KIMCHISTAN-BACKEND_DATABASE_PASSWORD'] %>
